"""
Seed 25 realistic mining H&S incidents so the triage dashboard looks real.
All AI fields are pre-filled (as if AI already processed them).
"""
from __future__ import annotations

import json
import uuid

from app.database import insert_incident, count_incidents

SEED_INCIDENTS = [
    {
        "reporter_name": "James Barton",
        "site_name": "Mount Isa Copper Mine",
        "location": "North Pit Ramp 3",
        "reported_at": "2025-03-08T09:40:00Z",
        "short_description": "Loader slipped near wet ramp. One worker twisted ankle. Oil leak visible.",
        "detailed_description": "At approximately 09:35, a CAT 994K loader was travelling down North Pit Ramp 3 when the operator noticed loss of traction on the wet surface. A maintenance worker inspecting nearby twisted his ankle while moving out of the way. Hydraulic oil leak visible near left rear wheel assembly. Area was not cordoned.",
        "people_impacted": 1,
        "injury_reported": 1,
        "immediate_danger": 1,
        "status": "open",
        "ai_title": "Slip injury near loader with hydraulic oil leak on wet ramp",
        "ai_summary": "A maintenance worker sustained an ankle injury after a loader lost traction on a wet ramp at North Pit Ramp 3. Hydraulic oil leak from the loader is creating an active slip hazard. The area remains uncordoned.",
        "ai_categories": json.dumps(["Slip/Fall", "Equipment Hazard", "Environmental Hazard"]),
        "ai_severity": "High",
        "ai_priority": "P1",
        "ai_confidence": 0.92,
        "ai_severity_rationale": "High priority: injury reported, active oil spill creating ongoing slip risk, area not yet isolated.",
        "ai_recommended_actions": json.dumps(["Cordon off Ramp 3 immediately", "Take loader out of service for hydraulic inspection", "Provide first aid to injured worker", "Deploy spill containment on oil leak", "Notify site safety supervisor"]),
        "ai_root_causes": json.dumps(["Hydraulic system failure on loader", "Wet ramp surface without adequate drainage", "No pre-work hazard assessment for wet conditions"]),
        "ai_extracted_entities": json.dumps({"equipment": ["CAT 994K loader"], "substances": ["hydraulic oil"], "body_parts_injured": ["ankle"], "personnel_roles": ["maintenance worker", "loader operator"], "environmental_factors": ["wet surface"]}),
        "ai_themes": json.dumps(["Slip & Fall Hazards", "Equipment Maintenance"]),
    },
    {
        "reporter_name": "Sarah Mitchell",
        "site_name": "Ravensworth Coal Mine",
        "location": "Conveyor Belt B12",
        "reported_at": "2025-03-08T11:15:00Z",
        "short_description": "Conveyor belt guard missing. Worker's glove caught in roller.",
        "detailed_description": "During routine coal transfer operation, operator noticed the safety guard on Conveyor B12 was missing. While attempting to clear a blockage, the operator's right glove was caught in the tail roller. Glove was pulled off but no skin contact with roller. Emergency stop activated. Belt was running at full speed.",
        "people_impacted": 1,
        "injury_reported": 0,
        "immediate_danger": 1,
        "status": "open",
        "ai_title": "Near-miss: glove entanglement at unguarded conveyor roller",
        "ai_summary": "An operator's glove was caught in the tail roller of Conveyor B12 after the safety guard was found missing. The glove was pulled off without injury. This is a serious near-miss with potential for amputation.",
        "ai_categories": json.dumps(["Equipment Hazard", "PPE Violation", "Near-Miss"]),
        "ai_severity": "High",
        "ai_priority": "P1",
        "ai_confidence": 0.95,
        "ai_severity_rationale": "Critical near-miss: missing guard on active conveyor with entanglement risk. Could easily have resulted in amputation.",
        "ai_recommended_actions": json.dumps(["Lock out/tag out Conveyor B12 immediately", "Inspect all conveyor guards on site", "Investigate why guard was removed and not replaced", "Retrain operators on clearing blockages safely", "Issue safety alert to all shifts"]),
        "ai_root_causes": json.dumps(["Safety guard removed and not replaced after maintenance", "Operator attempted to clear blockage while belt was running", "No pre-task inspection checklist enforced"]),
        "ai_extracted_entities": json.dumps({"equipment": ["Conveyor Belt B12", "tail roller"], "substances": [], "body_parts_injured": ["hand (near-miss)"], "personnel_roles": ["operator"], "environmental_factors": []}),
        "ai_themes": json.dumps(["Equipment Maintenance", "PPE Compliance"]),
    },
    {
        "reporter_name": "David Kowalski",
        "site_name": "Mount Isa Copper Mine",
        "location": "Underground Level 4 - Stope 7",
        "reported_at": "2025-03-07T14:20:00Z",
        "short_description": "Rock fall from unsupported roof in stope area. Two workers evacuated.",
        "detailed_description": "At 14:15 a section of the roof in Stope 7 on Level 4 collapsed without warning. Approximately 2 tonnes of rock fell. Two drill operators were working approximately 15m from the fall zone and were evacuated. No injuries but significant dust cloud reduced visibility. Ground support bolts in the area were last inspected 3 weeks ago.",
        "people_impacted": 2,
        "injury_reported": 0,
        "immediate_danger": 1,
        "status": "open",
        "ai_title": "Roof collapse in underground stope — two workers evacuated safely",
        "ai_summary": "Approximately 2 tonnes of rock fell from an unsupported roof section in Stope 7, Level 4. Two drill operators were evacuated without injury. Ground support was last inspected 3 weeks prior. The area remains unstable.",
        "ai_categories": json.dumps(["Structural", "Near-Miss"]),
        "ai_severity": "Critical",
        "ai_priority": "P1",
        "ai_confidence": 0.97,
        "ai_severity_rationale": "Critical: major rock fall in underground environment, potential for fatalities, area likely remains unstable.",
        "ai_recommended_actions": json.dumps(["Barricade and restrict access to Stope 7 and adjacent areas", "Conduct geotechnical assessment of ground stability", "Review all ground support inspection schedules", "Brief all underground crews on incident", "Investigate adequacy of rock bolt spacing and installation"]),
        "ai_root_causes": json.dumps(["Inadequate ground support in stope area", "Extended interval between ground support inspections", "Possible geological weakness not identified in survey"]),
        "ai_extracted_entities": json.dumps({"equipment": ["rock bolts", "drill rigs"], "substances": ["rock dust"], "body_parts_injured": [], "personnel_roles": ["drill operators"], "environmental_factors": ["unstable roof", "dust cloud"]}),
        "ai_themes": json.dumps(["Structural Integrity", "Working at Height"]),
    },
    {
        "reporter_name": "Maria Torres",
        "site_name": "Collahuasi Copper Mine",
        "location": "Haul Road Section C - KM 12",
        "reported_at": "2025-03-08T06:30:00Z",
        "short_description": "Haul truck tyre blowout at speed. Truck veered off road.",
        "detailed_description": "A Komatsu 930E haul truck experienced a rear tyre blowout while travelling loaded at approximately 40 km/h on Haul Road C. The truck veered to the right and came to rest against a safety berm. Driver reports hearing a loud bang before losing partial steering control. No injury to driver. Tyre fragments scattered across road.",
        "people_impacted": 1,
        "injury_reported": 0,
        "immediate_danger": 0,
        "status": "in_review",
        "ai_title": "Haul truck tyre blowout causing road departure at KM 12",
        "ai_summary": "A loaded Komatsu 930E experienced a rear tyre blowout at 40 km/h on Haul Road C, veering off into a safety berm. The driver was uninjured. Tyre debris is scattered across the haul road.",
        "ai_categories": json.dumps(["Vehicle", "Equipment Hazard"]),
        "ai_severity": "High",
        "ai_priority": "P2",
        "ai_confidence": 0.88,
        "ai_severity_rationale": "High severity: tyre blowout at speed on haul road poses fatal risk. Only the berm prevented a more serious outcome.",
        "ai_recommended_actions": json.dumps(["Close Haul Road C Section KM 11-13 until debris cleared", "Inspect remaining tyres on the truck", "Review tyre maintenance records for the fleet", "Check berm integrity along full haul road", "Brief all truck operators on tyre monitoring"]),
        "ai_root_causes": json.dumps(["Possible tyre overloading or pressure issue", "Road surface conditions may have contributed", "Tyre age or wear beyond safe limits"]),
        "ai_extracted_entities": json.dumps({"equipment": ["Komatsu 930E haul truck"], "substances": [], "body_parts_injured": [], "personnel_roles": ["truck driver"], "environmental_factors": ["haul road surface"]}),
        "ai_themes": json.dumps(["Vehicle Safety", "Equipment Maintenance"]),
    },
    {
        "reporter_name": "Thomas Wright",
        "site_name": "Hail Creek Coal Mine",
        "location": "Workshop Bay 3",
        "reported_at": "2025-03-07T16:45:00Z",
        "short_description": "Welder suffered flash burn to eyes. Was not wearing proper face shield.",
        "detailed_description": "During repair welding on a dozer blade in Workshop Bay 3, the welder experienced a flash burn to both eyes. Investigation found he was using a cracked auto-darkening lens that was not filtering properly. He had reported the defective lens to his supervisor the day before but no replacement was provided. First aid administered on site, worker transported to clinic.",
        "people_impacted": 1,
        "injury_reported": 1,
        "immediate_danger": 0,
        "status": "assigned",
        "ai_title": "Welder flash burn from defective auto-darkening lens",
        "ai_summary": "A welder sustained flash burns to both eyes while welding with a defective auto-darkening lens in Workshop Bay 3. The defective equipment had been reported the previous day without replacement. Worker has been sent to the clinic.",
        "ai_categories": json.dumps(["PPE Violation", "Equipment Hazard"]),
        "ai_severity": "High",
        "ai_priority": "P2",
        "ai_confidence": 0.93,
        "ai_severity_rationale": "High: eye injury from known defective PPE that was reported but not addressed. Systemic failure in PPE management.",
        "ai_recommended_actions": json.dumps(["Immediately audit all welding PPE across workshops", "Ensure replacement PPE is available within 24 hours of any report", "Investigate supervisor response to PPE defect report", "Review PPE inventory and replacement procedures", "Follow up on worker's medical status"]),
        "ai_root_causes": json.dumps(["Defective PPE not replaced after reported", "Supervisor did not act on PPE defect report", "No backup PPE inventory available in workshop"]),
        "ai_extracted_entities": json.dumps({"equipment": ["auto-darkening welding lens", "dozer blade"], "substances": [], "body_parts_injured": ["eyes"], "personnel_roles": ["welder", "supervisor"], "environmental_factors": []}),
        "ai_themes": json.dumps(["PPE Compliance", "Equipment Maintenance"]),
    },
    {
        "reporter_name": "Robert Chen",
        "site_name": "Ravensworth Coal Mine",
        "location": "Fuel Storage Area D",
        "reported_at": "2025-03-06T08:10:00Z",
        "short_description": "Diesel spill from damaged transfer hose. Approximately 200L on ground.",
        "detailed_description": "During morning refuelling operations, a transfer hose split at the coupling, releasing approximately 200 litres of diesel onto the bunded containment area. Some diesel has overflowed the bund into surrounding soil. Spill kit deployed. No ignition sources nearby. Environmental team notified.",
        "people_impacted": 0,
        "injury_reported": 0,
        "immediate_danger": 0,
        "status": "in_review",
        "ai_title": "200L diesel spill from split transfer hose at fuel storage",
        "ai_summary": "A transfer hose coupling failed during refuelling, spilling approximately 200L of diesel. Some fuel has breached the bund containment into surrounding soil. Spill kit has been deployed and environmental team notified.",
        "ai_categories": json.dumps(["Chemical/Spill", "Environmental Hazard"]),
        "ai_severity": "Medium",
        "ai_priority": "P3",
        "ai_confidence": 0.90,
        "ai_severity_rationale": "Medium: contained spill with no injuries, but soil contamination requires environmental remediation.",
        "ai_recommended_actions": json.dumps(["Complete spill containment and recovery", "Sample soil for contamination assessment", "Replace all hoses of same age/type at fuel storage", "Review bund capacity vs maximum spill scenario", "File environmental incident report"]),
        "ai_root_causes": json.dumps(["Hose coupling fatigue or wear", "Insufficient hose inspection schedule", "Bund capacity may be undersized"]),
        "ai_extracted_entities": json.dumps({"equipment": ["transfer hose", "fuel coupling"], "substances": ["diesel fuel"], "body_parts_injured": [], "personnel_roles": ["refuelling operator"], "environmental_factors": ["soil contamination"]}),
        "ai_themes": json.dumps(["Chemical Safety", "Environmental Hazard"]),
    },
    {
        "reporter_name": "Angela Price",
        "site_name": "Collahuasi Copper Mine",
        "location": "Processing Plant - Crusher Area",
        "reported_at": "2025-03-07T10:00:00Z",
        "short_description": "Excessive dust levels at crusher. Workers complaining of breathing difficulty.",
        "detailed_description": "Multiple workers in the crusher area have reported excessive dust levels and difficulty breathing over the past two shifts. Dust suppression sprays appear to be malfunctioning - low water pressure observed. Three workers have been reassigned. Air monitoring shows PM10 levels at 3x the exposure limit.",
        "people_impacted": 3,
        "injury_reported": 0,
        "immediate_danger": 1,
        "status": "open",
        "ai_title": "Excessive dust exposure at crusher — PM10 at 3x limit",
        "ai_summary": "Multiple workers report breathing difficulties at the crusher area due to failed dust suppression. Air monitoring confirms PM10 levels at three times the occupational exposure limit. Three workers have been reassigned.",
        "ai_categories": json.dumps(["Environmental Hazard", "Equipment Hazard"]),
        "ai_severity": "High",
        "ai_priority": "P1",
        "ai_confidence": 0.94,
        "ai_severity_rationale": "High/P1: active exposure above OEL with multiple workers affected. Respiratory health risk is immediate and ongoing.",
        "ai_recommended_actions": json.dumps(["Shut down crusher until dust suppression is restored", "Provide RPE (respiratory protective equipment) to all crusher area personnel", "Repair water supply to dust suppression system", "Conduct health surveillance on affected workers", "Increase air monitoring frequency"]),
        "ai_root_causes": json.dumps(["Dust suppression system failure - low water pressure", "Possible water supply line blockage", "Maintenance not flagging dust suppression degradation"]),
        "ai_extracted_entities": json.dumps({"equipment": ["crusher", "dust suppression sprays"], "substances": ["respirable dust (PM10)"], "body_parts_injured": ["respiratory system"], "personnel_roles": ["crusher operators"], "environmental_factors": ["airborne dust"]}),
        "ai_themes": json.dumps(["Environmental Hazard", "Equipment Maintenance"]),
    },
    {
        "reporter_name": "Kevin Brooks",
        "site_name": "Mount Isa Copper Mine",
        "location": "Surface Workshop - Electrical Bay",
        "reported_at": "2025-03-05T13:30:00Z",
        "short_description": "Electrical arc flash during switchgear maintenance. No injury.",
        "detailed_description": "During planned maintenance on 11kV switchgear, an arc flash occurred when a panel was opened. The electrician was wearing full arc flash PPE and was uninjured. Investigation found the lock-out tag-out procedure was correctly followed but residual stored energy in a capacitor bank was not discharged. Flash was contained within the arc-rated enclosure.",
        "people_impacted": 1,
        "injury_reported": 0,
        "immediate_danger": 0,
        "status": "closed",
        "ai_title": "Arc flash during 11kV switchgear maintenance — PPE prevented injury",
        "ai_summary": "An arc flash occurred during 11kV switchgear maintenance due to undischarged capacitor bank energy. The electrician's arc flash PPE prevented injury. LOTO was followed but stored energy discharge step was missed.",
        "ai_categories": json.dumps(["Electrical", "Near-Miss"]),
        "ai_severity": "High",
        "ai_priority": "P2",
        "ai_confidence": 0.91,
        "ai_severity_rationale": "High: arc flash at 11kV is potentially fatal. Only proper PPE prevented serious injury.",
        "ai_recommended_actions": json.dumps(["Review all LOTO procedures to include stored energy discharge", "Verify capacitor discharge procedures across all HV equipment", "Commend correct PPE usage", "Update switchgear maintenance SOP", "Share learnings with all electrical teams"]),
        "ai_root_causes": json.dumps(["Stored energy discharge step not in LOTO procedure", "Capacitor bank energy not accounted for in isolation plan"]),
        "ai_extracted_entities": json.dumps({"equipment": ["11kV switchgear", "capacitor bank"], "substances": [], "body_parts_injured": [], "personnel_roles": ["electrician"], "environmental_factors": []}),
        "ai_themes": json.dumps(["Electrical Safety", "Equipment Maintenance"]),
    },
    {
        "reporter_name": "Lisa Fernandez",
        "site_name": "Hail Creek Coal Mine",
        "location": "Open Pit - Bench 5",
        "reported_at": "2025-03-08T07:00:00Z",
        "short_description": "Excavator operator reports fatigue. Nearly struck light vehicle.",
        "detailed_description": "At shift start, an excavator operator on Bench 5 reports feeling fatigued after working 5 consecutive 12-hour night shifts. During his first swing of the shift, the excavator boom nearly struck a parked light vehicle that he did not see. No contact made. The operator self-reported and stood down voluntarily.",
        "people_impacted": 1,
        "injury_reported": 0,
        "immediate_danger": 0,
        "status": "open",
        "ai_title": "Fatigue-related near-miss — excavator nearly struck light vehicle",
        "ai_summary": "A fatigued excavator operator on his fifth consecutive 12-hour night shift nearly struck a parked light vehicle at Bench 5. The operator self-reported and stood down. No contact or injury occurred.",
        "ai_categories": json.dumps(["Vehicle", "Near-Miss"]),
        "ai_severity": "High",
        "ai_priority": "P2",
        "ai_confidence": 0.89,
        "ai_severity_rationale": "High: fatigue-induced near-miss with heavy equipment could easily be fatal. Systemic roster issue.",
        "ai_recommended_actions": json.dumps(["Commend operator for self-reporting", "Review roster for compliance with fatigue management policy", "Assess all operators on extended night rotations", "Implement pre-shift fatigue assessment", "Review light vehicle parking exclusion zones around excavators"]),
        "ai_root_causes": json.dumps(["5 consecutive 12-hour night shifts causing fatigue", "Light vehicle parked within excavator swing radius", "No pre-shift fatigue screening"]),
        "ai_extracted_entities": json.dumps({"equipment": ["excavator", "light vehicle"], "substances": [], "body_parts_injured": [], "personnel_roles": ["excavator operator"], "environmental_factors": ["night shift fatigue"]}),
        "ai_themes": json.dumps(["Fatigue & Human Factors", "Vehicle Safety"]),
    },
    {
        "reporter_name": "Ahmed Hassan",
        "site_name": "Collahuasi Copper Mine",
        "location": "Tailings Dam Wall - Section E",
        "reported_at": "2025-03-06T15:20:00Z",
        "short_description": "Crack observed in tailings dam wall. Seepage visible.",
        "detailed_description": "During routine dam inspection, a longitudinal crack approximately 8m long and 3cm wide was observed on the downstream face of the tailings dam in Section E. Minor seepage of turbid water is visible at the toe of the wall below the crack. The dam monitoring piezometers in this section have shown gradually increasing pore pressure over the last month. Dam safety engineer has been notified.",
        "people_impacted": 0,
        "injury_reported": 0,
        "immediate_danger": 1,
        "status": "open",
        "ai_title": "Tailings dam wall crack with seepage — rising pore pressure",
        "ai_summary": "An 8m longitudinal crack with seepage found on the tailings dam downstream face in Section E. Piezometer data shows increasing pore pressure over the past month. This is a potential dam stability concern requiring urgent geotechnical assessment.",
        "ai_categories": json.dumps(["Structural", "Environmental Hazard"]),
        "ai_severity": "Critical",
        "ai_priority": "P1",
        "ai_confidence": 0.96,
        "ai_severity_rationale": "Critical: tailings dam integrity issue with active seepage and rising pore pressures. Potential catastrophic failure risk.",
        "ai_recommended_actions": json.dumps(["Activate dam emergency response plan", "Increase monitoring frequency on all piezometers", "Deploy geotechnical engineer for immediate assessment", "Prepare downstream evacuation if needed", "Notify regulatory authority as per dam safety requirements", "Install additional monitoring instruments near crack"]),
        "ai_root_causes": json.dumps(["Rising pore water pressure in dam body", "Possible inadequate drainage system", "Foundation conditions may be contributing to differential settlement"]),
        "ai_extracted_entities": json.dumps({"equipment": ["tailings dam", "piezometers"], "substances": ["tailings water"], "body_parts_injured": [], "personnel_roles": ["dam inspector", "dam safety engineer"], "environmental_factors": ["increasing pore pressure", "seepage"]}),
        "ai_themes": json.dumps(["Structural Integrity", "Environmental Hazard"]),
    },
    {
        "reporter_name": "Daniel Moore",
        "site_name": "Ravensworth Coal Mine",
        "location": "Loading Bay 2",
        "reported_at": "2025-03-05T10:45:00Z",
        "short_description": "Forklift collision with racking system. Pallet fell from height.",
        "detailed_description": "A forklift operator reversing in Loading Bay 2 collided with a storage rack, dislodging a 500kg pallet from the third tier (approximately 4m height). The pallet fell to the ground approximately 2m from two workers who were sorting inventory. No one was struck. Forklift reverse camera was reported as non-functional.",
        "people_impacted": 2,
        "injury_reported": 0,
        "immediate_danger": 0,
        "status": "in_review",
        "ai_title": "Forklift collision caused pallet fall near workers — reverse camera inoperative",
        "ai_summary": "A forklift with a non-functional reverse camera struck a storage rack in Loading Bay 2, causing a 500kg pallet to fall from 4m height, landing 2m from two workers. No injuries occurred.",
        "ai_categories": json.dumps(["Vehicle", "Working at Height", "Near-Miss"]),
        "ai_severity": "High",
        "ai_priority": "P2",
        "ai_confidence": 0.92,
        "ai_severity_rationale": "High: 500kg falling from 4m is potentially fatal. Two workers narrowly avoided being struck. Equipment safety system was non-functional.",
        "ai_recommended_actions": json.dumps(["Take forklift out of service until camera repaired", "Inspect all forklift safety systems fleet-wide", "Review loading bay traffic management plan", "Install rack impact protection barriers", "Retrain forklift operators on pre-use checks"]),
        "ai_root_causes": json.dumps(["Forklift reverse camera non-functional", "Pre-use vehicle inspection not detecting camera fault", "No physical barriers protecting racking from vehicle impact"]),
        "ai_extracted_entities": json.dumps({"equipment": ["forklift", "storage rack", "reverse camera"], "substances": [], "body_parts_injured": [], "personnel_roles": ["forklift operator", "warehouse workers"], "environmental_factors": []}),
        "ai_themes": json.dumps(["Vehicle Safety", "Working at Height"]),
    },
    {
        "reporter_name": "Patricia Nguyen",
        "site_name": "Mount Isa Copper Mine",
        "location": "Underground Level 6 - Access Decline",
        "reported_at": "2025-03-06T22:15:00Z",
        "short_description": "Ventilation failure in underground decline. Gas readings elevated.",
        "detailed_description": "Main ventilation fan serving the Level 6 access decline tripped at 22:00. By 22:10, gas monitoring detected CO at 35ppm (limit 30ppm) and methane at 0.8% (limit 1%). Four workers in the decline were evacuated using emergency refuge protocols. Ventilation restored after backup fan activated at 22:30. Workers report mild headaches.",
        "people_impacted": 4,
        "injury_reported": 0,
        "immediate_danger": 1,
        "status": "open",
        "ai_title": "Underground ventilation failure with elevated CO and methane levels",
        "ai_summary": "Main ventilation fan failure in Level 6 access decline led to CO levels at 35ppm and methane at 0.8%. Four workers evacuated via emergency refuge. Ventilation restored via backup fan after 30 minutes. Workers reported mild headaches.",
        "ai_categories": json.dumps(["Environmental Hazard", "Equipment Hazard", "Confined Space"]),
        "ai_severity": "Critical",
        "ai_priority": "P1",
        "ai_confidence": 0.96,
        "ai_severity_rationale": "Critical: underground gas accumulation is life-threatening. Multiple workers exposed. Methane approaching explosive limit.",
        "ai_recommended_actions": json.dumps(["Keep Level 6 decline evacuated until gas levels normalize", "Investigate root cause of main fan trip", "Medical assessment for all four evacuated workers", "Review backup ventilation auto-start reliability", "Verify all gas monitoring stations are functional", "Review emergency refuge procedures"]),
        "ai_root_causes": json.dumps(["Main ventilation fan mechanical/electrical failure", "Backup fan did not auto-start (30 min delay)", "Possible methane ingress from geological source"]),
        "ai_extracted_entities": json.dumps({"equipment": ["main ventilation fan", "backup fan", "gas monitoring system"], "substances": ["carbon monoxide (CO)", "methane"], "body_parts_injured": ["respiratory (headaches)"], "personnel_roles": ["underground workers"], "environmental_factors": ["poor ventilation", "gas accumulation"]}),
        "ai_themes": json.dumps(["Confined Space", "Equipment Maintenance", "Environmental Hazard"]),
    },
    {
        "reporter_name": "Mark Sullivan",
        "site_name": "Hail Creek Coal Mine",
        "location": "Haul Road - Intersection J4",
        "reported_at": "2025-03-07T05:50:00Z",
        "short_description": "Two haul trucks near collision at intersection. Traffic lights malfunctioning.",
        "detailed_description": "At intersection J4, two Komatsu 830E haul trucks nearly collided when the intersection traffic lights were stuck on green in both directions. Truck 1 was loaded heading east, Truck 2 empty heading north. Both drivers applied emergency brakes and stopped approximately 5m apart. Traffic light system was commissioned 2 weeks ago.",
        "people_impacted": 2,
        "injury_reported": 0,
        "immediate_danger": 1,
        "status": "open",
        "ai_title": "Near head-on collision at intersection — traffic lights showing green both directions",
        "ai_summary": "Two haul trucks nearly collided at Intersection J4 when traffic lights showed green in both directions simultaneously. Trucks stopped 5m apart after emergency braking. The traffic system was recently commissioned.",
        "ai_categories": json.dumps(["Vehicle", "Near-Miss", "Equipment Hazard"]),
        "ai_severity": "Critical",
        "ai_priority": "P1",
        "ai_confidence": 0.95,
        "ai_severity_rationale": "Critical: near head-on collision between loaded haul trucks. Combined weight >500 tonnes. Traffic control system failure creates ongoing risk at all controlled intersections.",
        "ai_recommended_actions": json.dumps(["Disable traffic lights and deploy manual traffic control", "Check all intersection traffic systems site-wide", "Investigate software/hardware fault in recently commissioned system", "Implement independent conflict monitoring on all traffic systems", "Brief all operators on intersection protocols when lights are unreliable"]),
        "ai_root_causes": json.dumps(["Traffic light commissioning defect", "No conflict monitoring/failsafe in traffic system", "Possible software logic error showing green both ways"]),
        "ai_extracted_entities": json.dumps({"equipment": ["Komatsu 830E haul trucks (x2)", "traffic light system"], "substances": [], "body_parts_injured": [], "personnel_roles": ["haul truck drivers"], "environmental_factors": ["early morning low visibility"]}),
        "ai_themes": json.dumps(["Vehicle Safety", "Equipment Maintenance"]),
    },
    {
        "reporter_name": "Sandra Lee",
        "site_name": "Collahuasi Copper Mine",
        "location": "Acid Plant - Pipe Gallery",
        "reported_at": "2025-03-05T09:00:00Z",
        "short_description": "Sulfuric acid leak from corroded pipe flange. Small spill contained.",
        "detailed_description": "A maintenance inspector found sulfuric acid (98% concentration) leaking from a corroded flange on a 150mm pipe in the acid plant pipe gallery. Approximately 5 litres had pooled within the bunded area. Area was evacuated, acid-resistant PPE deployed, and the leak was isolated by closing upstream valve. Pipe section is 12 years old and was due for replacement next month.",
        "people_impacted": 0,
        "injury_reported": 0,
        "immediate_danger": 0,
        "status": "assigned",
        "ai_title": "Sulfuric acid leak from corroded pipe flange in acid plant",
        "ai_summary": "A 98% sulfuric acid leak from a corroded 150mm pipe flange was found in the acid plant pipe gallery. ~5L contained in bund. The pipe section is 12 years old and was scheduled for replacement next month.",
        "ai_categories": json.dumps(["Chemical/Spill", "Equipment Hazard"]),
        "ai_severity": "Medium",
        "ai_priority": "P3",
        "ai_confidence": 0.88,
        "ai_severity_rationale": "Medium: hazardous substance leak but contained within bund, no exposure, and successfully isolated.",
        "ai_recommended_actions": json.dumps(["Expedite replacement of corroded pipe section", "Neutralize and clean up spill in bund", "Inspect adjacent pipe sections of similar age", "Review corrosion inspection program for acid plant", "Confirm PPE availability for acid leak response"]),
        "ai_root_causes": json.dumps(["Corrosion of aging pipe flange", "Replacement scheduled but not yet executed", "Corrosion rate possibly underestimated"]),
        "ai_extracted_entities": json.dumps({"equipment": ["150mm acid pipe", "pipe flange", "upstream isolation valve"], "substances": ["sulfuric acid (98%)"], "body_parts_injured": [], "personnel_roles": ["maintenance inspector"], "environmental_factors": []}),
        "ai_themes": json.dumps(["Chemical Safety", "Equipment Maintenance"]),
    },
    {
        "reporter_name": "Paul Jackson",
        "site_name": "Ravensworth Coal Mine",
        "location": "ROM Pad",
        "reported_at": "2025-03-08T12:30:00Z",
        "short_description": "Dozer operator heat stress. Temperature 42°C. Worker collapsed.",
        "detailed_description": "A dozer operator working on the ROM pad collapsed after 4 hours of operation in 42°C ambient temperature. Cab air conditioning had failed at the start of shift but the operator continued working. Fellow workers found him unresponsive in the cab. First aid administered, cold water and shade provided. Ambulance called. Worker regained consciousness.",
        "people_impacted": 1,
        "injury_reported": 1,
        "immediate_danger": 0,
        "status": "open",
        "ai_title": "Heat stress collapse — dozer operator in 42°C with failed AC",
        "ai_summary": "A dozer operator collapsed from heat stress after 4 hours in 42°C with a failed cab air conditioning unit. The operator was found unresponsive, regained consciousness after first aid, and an ambulance was called.",
        "ai_categories": json.dumps(["Environmental Hazard", "Equipment Hazard"]),
        "ai_severity": "High",
        "ai_priority": "P2",
        "ai_confidence": 0.93,
        "ai_severity_rationale": "High: heat stroke can be fatal. Worker was unresponsive. Failed AC was a known issue that should have prevented operation.",
        "ai_recommended_actions": json.dumps(["Medevac worker to hospital for heat stroke assessment", "Stop all outdoor work until heat management controls confirmed", "Inspect AC systems on all mobile equipment", "Implement mandatory work-rest cycles in extreme heat", "Review heat stress management policy and trigger temperatures"]),
        "ai_root_causes": json.dumps(["Cab air conditioning failure not reported/actioned", "Operator continued working despite failed AC in extreme heat", "No mandatory heat stress monitoring for outdoor workers"]),
        "ai_extracted_entities": json.dumps({"equipment": ["dozer", "cab air conditioning"], "substances": [], "body_parts_injured": ["whole body (heat stress)"], "personnel_roles": ["dozer operator"], "environmental_factors": ["42°C ambient temperature", "failed air conditioning"]}),
        "ai_themes": json.dumps(["Fatigue & Human Factors", "Environmental Hazard", "Equipment Maintenance"]),
    },
    {
        "reporter_name": "George Petrov",
        "site_name": "Mount Isa Copper Mine",
        "location": "Surface - Near Admin Building",
        "reported_at": "2025-03-04T11:00:00Z",
        "short_description": "Worker tripped on uneven pathway. Sprained wrist.",
        "detailed_description": "An administrative worker tripped on a raised concrete slab on the walkway between the admin building and the car park. She fell forward and braced with her hands, spraining her left wrist. The raised slab has been a known hazard for 2 months with no repair action taken. A temporary hazard marker was placed but had blown away.",
        "people_impacted": 1,
        "injury_reported": 1,
        "immediate_danger": 0,
        "status": "closed",
        "ai_title": "Trip on known uneven pathway — wrist sprain",
        "ai_summary": "An admin worker tripped on a raised concrete slab (known hazard for 2 months) and sprained her wrist. The temporary hazard marker had blown away and no permanent repair had been made.",
        "ai_categories": json.dumps(["Slip/Fall"]),
        "ai_severity": "Low",
        "ai_priority": "P4",
        "ai_confidence": 0.95,
        "ai_severity_rationale": "Low: minor injury (sprain), but the known unrepaired hazard is a management concern.",
        "ai_recommended_actions": json.dumps(["Repair raised concrete slab immediately", "Audit all walkways for trip hazards", "Review process for closing out identified hazards", "Install permanent barriers around hazards pending repair"]),
        "ai_root_causes": json.dumps(["Known hazard not repaired for 2 months", "Temporary marker ineffective (blown away)", "No follow-up process to ensure hazard closure"]),
        "ai_extracted_entities": json.dumps({"equipment": [], "substances": [], "body_parts_injured": ["left wrist"], "personnel_roles": ["administrative worker"], "environmental_factors": ["uneven concrete slab"]}),
        "ai_themes": json.dumps(["Slip & Fall Hazards"]),
    },
    {
        "reporter_name": "Rachel Brown",
        "site_name": "Hail Creek Coal Mine",
        "location": "Wash Plant - Thickener Area",
        "reported_at": "2025-03-06T14:00:00Z",
        "short_description": "Flocculant chemical drum unsecured on pallet. Drum fell and split.",
        "detailed_description": "An unsecured 200L drum of polyacrylamide flocculant fell from a pallet during forklift transport near the thickener. The drum split on impact, releasing its contents onto the concrete pad. Two workers slipped in the spilled chemical. No injuries beyond minor bruising. Chemical is non-toxic but extremely slippery when wet.",
        "people_impacted": 2,
        "injury_reported": 0,
        "immediate_danger": 0,
        "status": "in_review",
        "ai_title": "Chemical drum fall — flocculant spill causes slip hazard at thickener",
        "ai_summary": "A 200L drum of polyacrylamide flocculant fell from an unsecured pallet during forklift transport, splitting on impact. Two workers slipped in the spill. Minor bruising only. The chemical is non-toxic but extremely slippery.",
        "ai_categories": json.dumps(["Chemical/Spill", "Slip/Fall"]),
        "ai_severity": "Medium",
        "ai_priority": "P3",
        "ai_confidence": 0.87,
        "ai_severity_rationale": "Medium: non-toxic chemical but created significant slip hazard. Two workers fell. Load securing procedures not followed.",
        "ai_recommended_actions": json.dumps(["Clean up flocculant spill with absorbent material", "Review chemical drum securing procedures for forklift transport", "Audit all chemical storage and handling areas", "Brief forklift operators on load securing requirements", "Place wet floor / slip hazard signs until cleanup complete"]),
        "ai_root_causes": json.dumps(["Drum not secured on pallet during transport", "Forklift operator did not verify load stability", "No load retention mechanism on pallet"]),
        "ai_extracted_entities": json.dumps({"equipment": ["forklift", "200L drum", "pallet"], "substances": ["polyacrylamide flocculant"], "body_parts_injured": [], "personnel_roles": ["forklift operator", "plant workers"], "environmental_factors": ["slippery surface"]}),
        "ai_themes": json.dumps(["Chemical Safety", "Slip & Fall Hazards"]),
    },
    {
        "reporter_name": "Nathan Reid",
        "site_name": "Collahuasi Copper Mine",
        "location": "Maintenance Workshop",
        "reported_at": "2025-03-07T08:30:00Z",
        "short_description": "Overhead crane chain broke during lift. Load dropped from 2m.",
        "detailed_description": "During a planned lift of a 3-tonne pump motor in the maintenance workshop, the chain on the 10-tonne overhead crane snapped at approximately 2m height. The motor fell onto the work platform below, damaging the platform and nearby tooling. The area had been cleared of personnel as per lift plan. Chain inspection records show the chain was last inspected 6 months ago.",
        "people_impacted": 0,
        "injury_reported": 0,
        "immediate_danger": 0,
        "status": "assigned",
        "ai_title": "Crane chain failure during lift — 3-tonne load dropped 2m",
        "ai_summary": "A 10-tonne overhead crane chain snapped during a planned 3-tonne lift, dropping a pump motor 2m onto a work platform. No injuries as the area was cleared per lift plan. Chain was last inspected 6 months ago.",
        "ai_categories": json.dumps(["Equipment Hazard", "Working at Height"]),
        "ai_severity": "High",
        "ai_priority": "P2",
        "ai_confidence": 0.93,
        "ai_severity_rationale": "High: chain failure during lift is potentially fatal. Good practice (area cleared) prevented injury. Systemic lifting equipment inspection concern.",
        "ai_recommended_actions": json.dumps(["Quarantine crane until full inspection complete", "Inspect all lifting chains and slings site-wide", "Review lifting equipment inspection frequency (6 months too long)", "Conduct metallurgical analysis on failed chain", "Audit compliance with lift plans across all workshops"]),
        "ai_root_causes": json.dumps(["Chain wear or fatigue beyond safe limit", "6-month inspection interval may be insufficient for this usage", "Possible overloading history not captured"]),
        "ai_extracted_entities": json.dumps({"equipment": ["10-tonne overhead crane", "lifting chain", "3-tonne pump motor"], "substances": [], "body_parts_injured": [], "personnel_roles": ["rigger", "crane operator"], "environmental_factors": []}),
        "ai_themes": json.dumps(["Equipment Maintenance", "Working at Height"]),
    },
    {
        "reporter_name": "Emily Watson",
        "site_name": "Ravensworth Coal Mine",
        "location": "Dragline - Machine 7",
        "reported_at": "2025-03-08T03:15:00Z",
        "short_description": "Dragline operator reports unusual vibration and grinding noise.",
        "detailed_description": "Night shift dragline operator on Machine 7 reports increasing vibration and grinding noise from the swing mechanism starting around 02:00. Operator reduced swing speed and notified maintenance. Preliminary inspection suggests possible bearing failure in the swing gear. Machine has accumulated 45,000 operating hours. No structural failure yet but continued operation could lead to catastrophic swing gear failure.",
        "people_impacted": 0,
        "injury_reported": 0,
        "immediate_danger": 0,
        "status": "open",
        "ai_title": "Dragline swing gear possible bearing failure at 45,000 hours",
        "ai_summary": "Machine 7 dragline operator reported vibration and grinding from the swing mechanism. Preliminary inspection suggests bearing failure. The machine has 45,000 hours and continued operation risks catastrophic failure.",
        "ai_categories": json.dumps(["Equipment Hazard"]),
        "ai_severity": "Medium",
        "ai_priority": "P3",
        "ai_confidence": 0.84,
        "ai_severity_rationale": "Medium: no immediate safety risk but potential for catastrophic failure if not addressed. Production impact also significant.",
        "ai_recommended_actions": json.dumps(["Shut down Machine 7 for detailed swing gear inspection", "Perform vibration analysis and oil sampling", "Order replacement bearings as precaution", "Review maintenance history for swing gear", "Assess production impact and plan alternative stripping"]),
        "ai_root_causes": json.dumps(["Bearing wear at end of service life (45,000 hours)", "Possible lubrication inadequacy", "Vibration monitoring may not have caught gradual degradation"]),
        "ai_extracted_entities": json.dumps({"equipment": ["dragline Machine 7", "swing gear", "bearings"], "substances": [], "body_parts_injured": [], "personnel_roles": ["dragline operator", "maintenance crew"], "environmental_factors": []}),
        "ai_themes": json.dumps(["Equipment Maintenance"]),
    },
    {
        "reporter_name": "Carlos Mendez",
        "site_name": "Collahuasi Copper Mine",
        "location": "Open Pit - Access Road",
        "reported_at": "2025-03-04T16:00:00Z",
        "short_description": "Rockfall on access road. Boulders blocking one lane.",
        "detailed_description": "Three boulders (estimated 0.5-1.5 tonnes each) fell from the highwall onto the main pit access road. One lane is completely blocked. No vehicles were in the area at the time. Recent blasting 200m away may have destabilized the wall. Highwall slope angle in this section exceeds design recommendations.",
        "people_impacted": 0,
        "injury_reported": 0,
        "immediate_danger": 1,
        "status": "open",
        "ai_title": "Highwall rockfall blocking pit access road after blasting",
        "ai_summary": "Three large boulders fell from the highwall onto the main pit access road. No vehicles were present. Recent blasting may have destabilized the wall, and the slope angle exceeds design limits.",
        "ai_categories": json.dumps(["Structural", "Vehicle"]),
        "ai_severity": "High",
        "ai_priority": "P1",
        "ai_confidence": 0.91,
        "ai_severity_rationale": "High/P1: rockfall onto active haul road is potentially fatal. Immediate danger remains as more rock may be unstable.",
        "ai_recommended_actions": json.dumps(["Close access road until geotechnical assessment complete", "Conduct highwall stability assessment in affected area", "Review blast design parameters for proximity to roads", "Clear debris with remote-controlled equipment", "Re-evaluate slope angle vs design recommendations", "Install rockfall catch fences if viable"]),
        "ai_root_causes": json.dumps(["Highwall slope angle exceeding design limits", "Blasting vibration destabilizing adjacent rock", "Possible geological discontinuities in highwall"]),
        "ai_extracted_entities": json.dumps({"equipment": [], "substances": [], "body_parts_injured": [], "personnel_roles": [], "environmental_factors": ["highwall instability", "blast vibration", "steep slope angle"]}),
        "ai_themes": json.dumps(["Structural Integrity", "Vehicle Safety"]),
    },
    {
        "reporter_name": "Jennifer Adams",
        "site_name": "Hail Creek Coal Mine",
        "location": "CHPP - Screen House",
        "reported_at": "2025-03-05T20:00:00Z",
        "short_description": "Worker struck by loose bolt ejected from vibrating screen.",
        "detailed_description": "During coal processing operations, a bolt from the vibrating screen assembly in the CHPP screen house ejected at high velocity, striking a process operator on the upper arm. The bolt had loosened due to vibration and was not captured by the guard. The operator was wearing a hard hat and safety glasses but the bolt struck below the PPE coverage area. Bruising and minor laceration. First aid applied.",
        "people_impacted": 1,
        "injury_reported": 1,
        "immediate_danger": 0,
        "status": "open",
        "ai_title": "Operator struck by ejected bolt from vibrating screen",
        "ai_summary": "A process operator was struck on the upper arm by a bolt that ejected from a vibrating screen in the CHPP. The bolt loosened from vibration and was not contained by the guard. Minor laceration and bruising.",
        "ai_categories": json.dumps(["Equipment Hazard"]),
        "ai_severity": "Medium",
        "ai_priority": "P3",
        "ai_confidence": 0.89,
        "ai_severity_rationale": "Medium: projectile from equipment caused minor injury. Higher-energy ejection or different trajectory could be fatal (head/eye).",
        "ai_recommended_actions": json.dumps(["Inspect all vibrating screen bolt torque and retention", "Review guard design to capture ejected fasteners", "Implement vibrating equipment bolt-check routine", "Consider self-locking fasteners for vibrating equipment", "Review PPE requirements for screen house operations"]),
        "ai_root_causes": json.dumps(["Bolt self-loosened from vibration", "Guard design does not contain ejected fasteners", "No routine bolt torque check program"]),
        "ai_extracted_entities": json.dumps({"equipment": ["vibrating screen", "bolt", "guard"], "substances": [], "body_parts_injured": ["upper arm"], "personnel_roles": ["process operator"], "environmental_factors": ["high vibration environment"]}),
        "ai_themes": json.dumps(["Equipment Maintenance"]),
    },
    {
        "reporter_name": "Yuki Tanaka",
        "site_name": "Mount Isa Copper Mine",
        "location": "Underground Level 3 - Magazine",
        "reported_at": "2025-03-03T07:30:00Z",
        "short_description": "Explosives magazine temperature monitoring system offline for 48 hours.",
        "detailed_description": "The automated temperature monitoring system for the underground explosives magazine on Level 3 has been offline for 48 hours. Manual temperature checks have been performed but there is no continuous monitoring or alarm capability. The magazine currently stores approximately 2 tonnes of emulsion explosives and 500 detonators. Ambient temperature in the area has been stable but seasonal heat is increasing.",
        "people_impacted": 0,
        "injury_reported": 0,
        "immediate_danger": 0,
        "status": "in_review",
        "ai_title": "Explosives magazine temperature monitoring offline for 48 hours",
        "ai_summary": "The temperature monitoring system for the underground explosives magazine has been offline for 48 hours. The magazine contains 2 tonnes of emulsion explosives and 500 detonators. Manual checks are being done but no continuous alarm capability.",
        "ai_categories": json.dumps(["Equipment Hazard", "Fire/Explosion"]),
        "ai_severity": "High",
        "ai_priority": "P2",
        "ai_confidence": 0.90,
        "ai_severity_rationale": "High: explosives storage without continuous monitoring is a critical safety and regulatory risk. Potential for catastrophic event if temperature exceedance is missed.",
        "ai_recommended_actions": json.dumps(["Expedite repair of temperature monitoring system", "Increase manual temperature check frequency to every 2 hours", "Review regulatory requirements for magazine monitoring", "Assess if magazine inventory should be reduced until system restored", "Notify mine manager and regulatory body if required"]),
        "ai_root_causes": json.dumps(["Monitoring system hardware or sensor failure", "No redundant monitoring system installed", "Repair prioritization may not reflect criticality of explosives storage"]),
        "ai_extracted_entities": json.dumps({"equipment": ["temperature monitoring system", "explosives magazine"], "substances": ["emulsion explosives", "detonators"], "body_parts_injured": [], "personnel_roles": [], "environmental_factors": ["increasing seasonal temperature"]}),
        "ai_themes": json.dumps(["Fire & Explosion", "Equipment Maintenance"]),
    },
    {
        "reporter_name": "Ian Crawford",
        "site_name": "Ravensworth Coal Mine",
        "location": "Pit Floor - Panel 3",
        "reported_at": "2025-03-08T14:45:00Z",
        "short_description": "Spontaneous combustion detected in coal stockpile. Smoke visible.",
        "detailed_description": "Visible smoke and an acrid smell detected from the coal stockpile at Panel 3 pit floor. Infrared survey confirms hotspot at approximately 180°C in the centre of the stockpile. The stockpile has been in place for 3 weeks. Wind is pushing smoke towards the active mining area. Fire crew on standby but advised not to apply water (risk of steam explosion). Plan is to excavate hot material with remote-controlled dozer.",
        "people_impacted": 0,
        "injury_reported": 0,
        "immediate_danger": 1,
        "status": "open",
        "ai_title": "Spontaneous combustion in coal stockpile — 180°C hotspot",
        "ai_summary": "Spontaneous combustion detected in a 3-week-old coal stockpile at Panel 3 with a 180°C hotspot. Smoke is drifting toward active mining areas. Remote excavation planned; water application avoided due to steam explosion risk.",
        "ai_categories": json.dumps(["Fire/Explosion", "Environmental Hazard"]),
        "ai_severity": "High",
        "ai_priority": "P1",
        "ai_confidence": 0.94,
        "ai_severity_rationale": "High/P1: active combustion with smoke exposure risk to workers. Steam explosion hazard if water applied. Requires immediate coordinated response.",
        "ai_recommended_actions": json.dumps(["Evacuate all personnel downwind of stockpile", "Deploy remote-controlled dozer to excavate hot material", "Establish exclusion zone around stockpile", "Monitor air quality for CO and particulates", "Review stockpile age limits and spontaneous combustion management plan", "Do NOT apply water — steam explosion risk"]),
        "ai_root_causes": json.dumps(["Coal stockpile stored too long (3 weeks) without turnover", "Possible high-reactivity coal seam", "No temperature monitoring on stockpiles"]),
        "ai_extracted_entities": json.dumps({"equipment": ["remote-controlled dozer", "infrared survey equipment"], "substances": ["coal", "smoke", "carbon monoxide"], "body_parts_injured": [], "personnel_roles": ["fire crew", "mining crew"], "environmental_factors": ["wind direction", "180°C hotspot"]}),
        "ai_themes": json.dumps(["Fire & Explosion", "Environmental Hazard"]),
    },
    {
        "reporter_name": "Helen Zhang",
        "site_name": "Collahuasi Copper Mine",
        "location": "Concentrator Building - Level 2",
        "reported_at": "2025-03-06T11:30:00Z",
        "short_description": "Worker fell through unsecured floor grating. Dropped 1.5m.",
        "detailed_description": "A process technician stepped onto a floor grating panel on Level 2 of the concentrator building that had been removed for maintenance and placed back without being secured. The panel tipped, and the worker fell approximately 1.5m to Level 1. The worker landed on a pipe rack and sustained bruised ribs and a sore back. The maintenance team had left for lunch without securing or barricading the opening.",
        "people_impacted": 1,
        "injury_reported": 1,
        "immediate_danger": 0,
        "status": "open",
        "ai_title": "Worker fell through unsecured floor grating — 1.5m drop",
        "ai_summary": "A technician fell 1.5m through an unsecured floor grating panel that had been removed for maintenance and left unbarricaded. The worker sustained bruised ribs and back pain after landing on a pipe rack.",
        "ai_categories": json.dumps(["Working at Height", "Slip/Fall"]),
        "ai_severity": "High",
        "ai_priority": "P2",
        "ai_confidence": 0.92,
        "ai_severity_rationale": "High: fall through floor opening could easily be fatal with greater height or different landing. Systemic failure in temporary opening management.",
        "ai_recommended_actions": json.dumps(["Secure all open floor grating panels immediately", "Audit all temporary openings site-wide", "Implement mandatory barricading for any removed grating", "Investigate why maintenance left without securing opening", "Review permit-to-work for floor penetration/removal work"]),
        "ai_root_causes": json.dumps(["Grating replaced without securing clips", "No barricade placed around unsecured panel", "Maintenance team left opening unattended"]),
        "ai_extracted_entities": json.dumps({"equipment": ["floor grating panel", "pipe rack"], "substances": [], "body_parts_injured": ["ribs", "back"], "personnel_roles": ["process technician", "maintenance team"], "environmental_factors": []}),
        "ai_themes": json.dumps(["Working at Height", "Slip & Fall Hazards"]),
    },
    {
        "reporter_name": "Brian O'Neil",
        "site_name": "Hail Creek Coal Mine",
        "location": "Water Dam - Pump Station",
        "reported_at": "2025-03-04T09:15:00Z",
        "short_description": "Snake found in pump station electrical cabinet. Worker startled, bumped head.",
        "detailed_description": "A pump station operator opened the main electrical cabinet for routine inspection and found a large brown snake coiled inside. The operator was startled and jumped back, hitting his head on a low-hanging pipe. Minor bump, no significant injury. The snake was identified as an eastern brown (highly venomous). Wildlife handler called to remove it. Cabinet sealing is poor with visible gaps.",
        "people_impacted": 1,
        "injury_reported": 1,
        "immediate_danger": 0,
        "status": "closed",
        "ai_title": "Venomous snake in electrical cabinet — worker bumped head",
        "ai_summary": "A highly venomous eastern brown snake was found in a pump station electrical cabinet. The startled operator bumped his head on a pipe. Wildlife handler removed the snake. Cabinet has poor sealing allowing wildlife entry.",
        "ai_categories": json.dumps(["Environmental Hazard"]),
        "ai_severity": "Low",
        "ai_priority": "P4",
        "ai_confidence": 0.82,
        "ai_severity_rationale": "Low: minor injury (bumped head), but venomous snake encounter warrants follow-up on cabinet sealing and wildlife management.",
        "ai_recommended_actions": json.dumps(["Seal all gaps in electrical cabinets at pump station", "Inspect other remote installations for wildlife entry points", "Brief workers on snake awareness and first aid", "Add snake bite kit to pump station first aid supplies", "Consider installing snake deterrent mesh on critical enclosures"]),
        "ai_root_causes": json.dumps(["Poor cabinet sealing allowing wildlife entry", "Remote location attractive to wildlife", "No wildlife proofing standard for field electrical enclosures"]),
        "ai_extracted_entities": json.dumps({"equipment": ["electrical cabinet", "pump station"], "substances": [], "body_parts_injured": ["head (minor bump)"], "personnel_roles": ["pump station operator"], "environmental_factors": ["venomous snake (eastern brown)"]}),
        "ai_themes": json.dumps(["Environmental Hazard"]),
    },
]


def seed_demo_data():
    """Insert seed incidents only if the database is empty."""
    if count_incidents() > 0:
        return

    import uuid as _uuid

    for incident in SEED_INCIDENTS:
        incident["id"] = str(_uuid.uuid4())
        insert_incident(incident)

    print(f"✓ Seeded {len(SEED_INCIDENTS)} demo incidents.")
